# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-21 04:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # ('carts','__first__'),
        ('products', '0001_initial'),
        ('account', '0001_initial'),
        # ('account','__first__')
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField(default=1)),
                ('productID', models.ForeignKey(db_column='ProductID', on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=13)),
                ('myBasket', models.ManyToManyField(through='carts.Basket', to='products.Product')),
            ],
        ),
        migrations.AddField(
            model_name='basket',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carts.User'),
        ),
    ]
