# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-26 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_applicant_point'),
        ('carts', '0002_companymoney'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('money', models.IntegerField(default=1)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Applicant')),
            ],
        ),
    ]
