# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-26 10:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_basket_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Applicant'),
        ),
    ]
