# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-30 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_auto_20170930_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='productID',
            field=models.ForeignKey(db_column='ProductID', on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
