# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-30 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_auto_20170930_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
