# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-01 07:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20171001_1406'),
        ('carts', '0005_auto_20170930_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=13)),
            ],
        ),
        migrations.AlterField(
            model_name='basket',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='basket',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carts.User'),
        ),
        migrations.AddField(
            model_name='user',
            name='myBasket',
            field=models.ManyToManyField(through='carts.Basket', to='products.Product'),
        ),
    ]
