# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-21 04:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('productID', models.ForeignKey(db_column='ProductID', on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='favorite.Account')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='myFav',
            field=models.ManyToManyField(through='favorite.Favorite', to='products.Product'),
        ),
    ]
