# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-26 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('productID', models.ForeignKey(db_column='ProductID', on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Applicant')),
            ],
        ),
    ]
