# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-21 17:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('favorite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='myFav',
        ),
        migrations.AlterField(
            model_name='favorite',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Applicant'),
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
