# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-26 11:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='userId',
        ),
    ]
