# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-01 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20171001_1406'),
        ('favorite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=13)),
            ],
        ),
        migrations.RemoveField(
            model_name='favitem',
            name='fav',
        ),
        migrations.RemoveField(
            model_name='favitem',
            name='product',
        ),
        migrations.AlterField(
            model_name='favorite',
            name='productID',
            field=models.ForeignKey(db_column='ProductID', on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='favorite.Account'),
        ),
        migrations.DeleteModel(
            name='FavItem',
        ),
        migrations.AddField(
            model_name='account',
            name='myFav',
            field=models.ManyToManyField(through='favorite.Favorite', to='products.Product'),
        ),
    ]
