# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-26 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20171126_1846'),
        ('account', '0003_remove_applicant_myfav'),
        ('favorite', '0002_remove_favorite_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('productID', models.ForeignKey(db_column='ProductID', on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Applicant')),
            ],
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='productID',
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
