# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-21 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proId', models.PositiveIntegerField(default=None)),
                ('userId', models.PositiveIntegerField(default=None)),
                ('userName', models.CharField(max_length=100)),
                ('comment', models.CharField(blank=True, max_length=250)),
                ('point', models.PositiveIntegerField(default=None)),
            ],
        ),
    ]
