# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-26 11:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 26, 18, 41, 52, 935661)),
        ),
    ]
