# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-30 07:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='isbn',
            new_name='idpro',
        ),
    ]
