# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-30 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20170930_0715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='idpro',
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
