# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-21 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_reviewproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewproduct',
            name='comment',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='reviewproduct',
            name='point',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='reviewproduct',
            name='proId',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='reviewproduct',
            name='userId',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='reviewproduct',
            name='userName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
