# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-26 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_date_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_modified',
            field=models.FloatField(null=True),
        ),
    ]
