# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-30 07:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20170930_0717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='Height',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='size_height',
            new_name='Length',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='size_thickness',
            new_name='cost',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='count',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='author',
            new_name='supplier',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='size_width',
            new_name='width',
        ),
        migrations.RemoveField(
            model_name='product',
            name='coverType',
        ),
        migrations.RemoveField(
            model_name='product',
            name='isMonocrome',
        ),
        migrations.RemoveField(
            model_name='product',
            name='paperType',
        ),
        migrations.RemoveField(
            model_name='product',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
    ]
