# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-26 12:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20171126_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 26, 19, 30, 12, 571758)),
        ),
    ]
