# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-26 17:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20171126_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 27, 0, 18, 44, 870162)),
        ),
    ]
