# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-30 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20170930_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(db_column='ProductID', primary_key=True, serialize=False),
        ),
    ]
