# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-21 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='point',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
