# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-01 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20170930_0722'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewPro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.PositiveIntegerField()),
                ('productId', models.PositiveIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('point', models.PositiveIntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Height',
            new_name='height',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Length',
            new_name='length',
        ),
    ]
