# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-01 07:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20170930_1843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Height',
            new_name='height',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Length',
            new_name='length',
        ),
    ]
