# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-26 20:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20171127_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 27, 3, 11, 35, 901205)),
        ),
    ]
