# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-25 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20171121_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
