# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-25 15:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_date_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 25, 15, 26, 14, 467311)),
        ),
    ]
