# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 09:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20171126_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 26, 16, 15, 47, 86850)),
        ),
    ]
