# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-26 10:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20171126_1724'),
        ('products', '0005_auto_20171126_0926'),
    ]

    operations = [
    ]
