# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-26 10:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_merge_20171126_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 26, 17, 51, 58, 984400)),
        ),
    ]
