# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_activated', models.CharField(choices=[('AC', 'Active'), ('CL', 'Closed'), ('WT', 'Waiting')], default='WT', max_length=2)),
                ('reset_password', models.CharField(choices=[('RS', 'Reset'), ('CL', 'Closed')], default='CL', max_length=2)),
                ('username', models.CharField(default=None, max_length=50, unique=True)),
                ('email', models.EmailField(default=None, max_length=128, unique=True)),
                ('firstname', models.CharField(default=None, max_length=128)),
                ('lastname', models.CharField(default=None, max_length=128)),
                ('password', models.CharField(default=None, max_length=128)),
                ('mobile', models.CharField(default=None, max_length=10)),
                ('address', models.CharField(default=None, max_length=512)),
                ('city', models.CharField(default=None, max_length=128)),
                ('state', models.CharField(default=None, max_length=128)),
                ('zipcode', models.CharField(default=None, max_length=5)),
            ],
        ),
    ]
