# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-25 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carts', '0001_initial'),
        ('account', '0001_initial'),
        ('favorite', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='myBasket',
            field=models.ManyToManyField(related_name='BasketProduct', through='carts.Basket', to='products.Product'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='myFav',
            field=models.ManyToManyField(related_name='FavProduct', through='favorite.Favorite', to='products.Product'),
        ),
    ]
