# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-26 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('carts', '0002_basket_userid'),
        ('favorite', '0002_favorite_userid'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='myBasket',
            field=models.ManyToManyField(related_name='BasketProduct', through='carts.Basket', to='products.Product'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='myFav',
            field=models.ManyToManyField(related_name='FavProduct', through='favorite.Favorite', to='products.Product'),
        ),
    ]
