# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='address',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='city',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='password',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='state',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='applicant',
            name='hashed_password',
            field=models.CharField(blank=True, max_length=130),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
