# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-26 11:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20171126_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='myFav',
        ),
    ]
