# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20171120_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='address',
            field=models.CharField(default=None, max_length=512),
        ),
        migrations.AddField(
            model_name='applicant',
            name='city',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AddField(
            model_name='applicant',
            name='firstname',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AddField(
            model_name='applicant',
            name='lastname',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AddField(
            model_name='applicant',
            name='mobile',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='applicant',
            name='state',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AddField(
            model_name='applicant',
            name='zipcode',
            field=models.CharField(default=None, max_length=5),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='email',
            field=models.EmailField(default=None, max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='hashed_password',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='username',
            field=models.CharField(default=None, max_length=50, unique=True),
        ),
    ]
