# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-19 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_applicant_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='is_activated',
            field=models.CharField(choices=[('AC', 'Active'), ('CL', 'Closed'), ('WT', 'Waiting')], default='WT', max_length=2),
        ),
        migrations.AddField(
            model_name='applicant',
            name='reset_password',
            field=models.CharField(choices=[('RS', 'Reset'), ('CL', 'Closed')], default='CL', max_length=2),
        ),
    ]
