# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-21 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20171121_0704'),
        ('carts', '0002_auto_20171121_1639'),
        ('account', '0003_auto_20171120_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='myBasket',
            field=models.ManyToManyField(through='carts.Basket', to='products.Product'),
        ),
    ]
