# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 09:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_shiping'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='shiping',
            new_name='Shipping',
        ),
    ]
