# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-26 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_applicant_myfav'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='point',
            field=models.IntegerField(default=0),
        ),
    ]
