# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 10:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20171126_1724'),
        ('account', '0004_auto_20171126_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='myShipping',
            field=models.ManyToManyField(related_name='ShippingProduct', through='account.Shipping', to='products.Product'),
        ),
        migrations.RemoveField(
            model_name='shipping',
            name='productID',
        ),
        migrations.AddField(
            model_name='shipping',
            name='productID',
            field=models.ForeignKey(db_column='ProductID', null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
