# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-21 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorite', '0002_auto_20171122_0034'),
        ('products', '0005_auto_20171121_0704'),
        ('account', '0004_applicant_mybasket'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='myFav',
            field=models.ManyToManyField(related_name='FavProduct', through='favorite.Favorite', to='products.Product'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='myBasket',
            field=models.ManyToManyField(related_name='BasketProduct', through='carts.Basket', to='products.Product'),
        ),
    ]
