"""
Django settings for SYOT project.

Generated by 'django-admin startproject' using Django 1.11.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'dl^a_7ll2$ipi9^@p=ic!81t!y5cr#sbec9#3gh*aqrd+spt4p'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

EMAIL_HOST =  'smtp.gmail.com'
EMAIL_HOST_USER = 'syotshopbkk@gmail.com'
EMAIL_HOST_PASSWORD = 'syot12345'
EMAIL_PORT = '587'
EMAIL_USE_TLS = True

# TEMPLATE_DEBUG = True

ALLOWED_HOSTS = [
    '0.0.0.0',
    'localhost',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres.search',
    # 'django.contrib.postgres'
    # 'django.contrib.postgresproducts',
    ####
    'products',
    'rest_framework',
    'carts',
    'favorite',
    'mathfilters',
    'account',
    'testuser',
    'bootstrapform',
    'widget_tweaks',
    'stripe'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'SYOT.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'SYOT.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }

DATABASES = {
    'default': {
        'NAME': 'syot_database',
        'ENGINE': 'django.db.backends.mysql',
        'USER': 'ubuntu',
        'PASSWORD': '1q2w3e4rsyot',
        'HOST': 'ec2-54-169-223-248.ap-southeast-1.compute.amazonaws.com',
        'PORT': '3306',
        'OPTIONS': {
            'read_default_file': '/static/my.ini',
        },
    }
}

#
# # my.cnf
# [client]
# database = syot_database
# user = 'ubuntu'
# password = ''
# default-character-set = utf8

# [mysqld]
# port = '3306'
# bind-address = '0.0.0.0'



# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
# MEDIA_URL = '/media/'

# MEDIA_ROOT = os.path.join(os.path.dirname(BASE_DIR), "static", "media")
#MEDIA_ROOT = '/Users/jmitch/Desktop/ecommerce/static/media/'

STATIC_ROOT = os.path.join(os.path.dirname(BASE_DIR), "static", "static_root")

if DEBUG :
    STATICFILES_DIRS = [
        os.path.join(BASE_DIR, "static"),
    ]
    MEDIA_URL = '/static/media/'
    MEDIA_ROOT = os.path.join(BASE_DIR, "static", "media")

STRIPE_PUBLISHABLE_KEY = 'pk_test_Mrdcgrtz1ddf7X3bIyLazfkQ'
STRIPE_SECRET_KEY = 'sk_test_w3jUVRVlbpFAdN96xBpdf99A'
